spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.98.84.10:3306/travel_v2?characterEncoding=utf-8&useSSL=false
    username: root
    password: Intrip1114..@314
  redis:
    host: 39.98.84.10
    port: 6379
    password: redis@2020*
